# Site settings
title: flow14, the blog
header-img: img/home-bg.jpg
email: hello@flow14.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://localhost:4000"
twitter_username: kylejohnston
github_username:  kylejohnston
facebook_username:  thekylejohnston

# Build settings
markdown: kramdown
highlighter: pygments
permalink: :year/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
